"""read state: memberships.last_read_message_id

Revision ID: 288a47108837
Revises: 3e79d72bf1f9
Create Date: 2026-06-18 23:53:47.172134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288a47108837'
down_revision: Union[str, Sequence[str], None] = '3e79d72bf1f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_read_message_id', sa.Uuid(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: mark existing members caught up to their channel's latest message,
    # so the new unread counter doesn't suddenly flag all history as unread.
    op.execute(
        """
        UPDATE memberships
        SET last_read_message_id = (
            SELECT max(messages.id) FROM messages
            WHERE messages.channel_id = memberships.channel_id
              AND messages.deleted_at IS NULL
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('last_read_message_id')

    # ### end Alembic commands ###
